services:
  node:
    image: qfortier/exos
    command: npm --prefix app/ run start
    working_dir: /workspace
    ports:
      - 3000:3000
      - 5555:5555
    links:
      - db
    volumes:
      - ./:/workspace
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
