services:
  node:
    image: qfortier/exos
    command: npm run dev
    working_dir: /app
    ports:
      - 3000:3000
      - 5555:5555
    links:
      - db
    volumes:
      - ./server/:/app
    env_file:
      - server/.env
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - server/.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
