services:
  node:
    image: qfortier/exos
    working_dir: /home/node/app
    ports:
      - 8080:8080
    links:
      - db
    volumes:
      - ./server/:/home/node/app
    env_file:
      - db.env
    environment:
      PGHOST: db

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - db.env
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
