services:
  node:
    build: .
    command: sleep infinity
    working_dir: /home/node/app
    ports:
      - 3000:3000
    links:
      - db
    env_file:
      - ../db.env
    environment:
      PGHOST: db
    volumes:
      - ../:/workspace/

  db:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ../db.env
    volumes:
      - ../sql:/docker-entrypoint-initdb.d
      # - ./data:/var/lib/postgresql/data
