version: '3.8'

services:
  app:
    image: node:latest
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    network_mode: service:db
    env_file:
      - ../sql.env

  db:
    image: qfortier/cpge-exos-sql
    env_file:
      - ../sql.env
