CREATE TABLE IF NOT EXISTS exercise (
	name VARCHAR(255) NOT NULL,
	path VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS subject (
	name VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS exercise_subject (
	id SERIAL PRIMARY KEY,
	exercise_path VARCHAR(255) NOT NULL REFERENCES exercise,
	subject_name VARCHAR(255) NOT NULL REFERENCES subject);
CREATE TABLE IF NOT EXISTS ds (
	name VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS exercise_ds (
	id SERIAL PRIMARY KEY,
	exercise_path VARCHAR(255) NOT NULL REFERENCES exercise,
	ds_name VARCHAR(255) NOT NULL REFERENCES ds);
CREATE TABLE IF NOT EXISTS language (
	name VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS exercise_language (
	id SERIAL PRIMARY KEY,
	exercise_path VARCHAR(255) NOT NULL REFERENCES exercise,
	language_name VARCHAR(255) NOT NULL REFERENCES language);
CREATE TABLE IF NOT EXISTS algorithm (
	name VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS exercise_algorithm (
	id SERIAL PRIMARY KEY,
	exercise_path VARCHAR(255) NOT NULL REFERENCES exercise,
	algorithm_name VARCHAR(255) NOT NULL REFERENCES algorithm);
CREATE TABLE IF NOT EXISTS classe (
	name VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE IF NOT EXISTS exercise_classe (
	id SERIAL PRIMARY KEY,
	exercise_path VARCHAR(255) NOT NULL REFERENCES exercise,
	classe_name VARCHAR(255) NOT NULL REFERENCES classe);
